### ISSUE TITLE
Full Stack projektin katselmointi

### ISSUE THREAD

**Issue by Kaltsoon** [Zatyri/g-app#2]
# Full Stack projektin katselmointi

Terve @Zatyri! Tässä lyhyt katselmointi Full Stack kurssin projektistasi. Katselmoinnissa esitetyt kommentit ovat parannusehdotuksia, joita voit _halutessasi_ ottaa huomioon tässä tai tulevissa projekteissasi. Mitään muutoksia tähän projektiin ei siis ole pakko tehdä suoritusmerkintää varten.

### Mitä tein?

- Kirjauduin sisään käyttäjä-oikeuksien käyttäjänä
- Vertailin puhelinliittymiä, nettiliittymiä ja tietoturvaa
- Lisäsin puhelinliittymän ostoskoriin
- Avasin ostoskorin
- Kirjauduin ulos
- Kirjauduin sisään admin-oikeuksien käyttäjänä
- Tutustuin admin-käyttäjän toiminallisuuteen
- Kirjauduin ulos

### Kokemus

- Selkeä ja tyylikäs käyttöliittymä, hyvää työtä! 🥇
- Geneerisen "React App"-faviconin voisi muuttaa kuvaavammaksi
- Muut kuin `/`-polun sivut eivät aukea suoraan selaimen osoiterivin kautta, kuten https://gappi.herokuapp.com/puheliittymat, vaan niihin pitää navigoida sovelluksen navigaatiopalkin kautta. Johtunee siitä, ettei `index.html`-tiedostoa tarjoilla muusta kuin `/`-polusta
- Lomakkeissa on selkeät virheilmoitukset
- Kun ostoskorissa on tuote ja sen avaa, tulee konsoliin seuraava virhe:

```
TypeError: Cannot read property 'monthlyPayment' of null
    at ShoppingCartCombined.jsx:21
    at Array.forEach (<anonymous>)
    at n (ShoppingCartCombined.jsx:20)
    at Ht (ShoppingCartCombined.jsx:58)
    at ia (react-dom.production.min.js:157)
    at Ks (react-dom.production.min.js:267)
    at ju (react-dom.production.min.js:250)
    at Eu (react-dom.production.min.js:250)
    at Su (react-dom.production.min.js:250)
    at vu (react-dom.production.min.js:243)
```

## Koodi

- Frontend-puolen koodi on selkeästi organisoitua, hyvä!
- Hyvää fragmenttien käyttöä GraphQL-kyselyissä! Esimerkiksi `SUBSCRIPTION_INFO`- ja `SUBSCRIPTION_INFO_WITH_OFFER`-fragmentit ovat melko samanlaisia. Voisiko `SUBSCRIPTION_INFO`-fragmenttia hyödyntää `SUBSCRIPTION_INFO_WITH_OFFER`-fragmentissa?

```javascript
export const SUBSCRIPTION_INFO_WITH_OFFER = gql`
  fragment SubscriptionInfoWithOffer on Subscription {
    offer
    offerLength
    bindingOffer
    offerValue
    oneTimeDiscount
    ...SubscriptionInfo
  }

  ${SUBSCRIPTION_INFO}
`;
```
- Tyylejä kannattaa eritellä niitä käyttävien komponenttien mukaan omiksi kansiomoduuleikseen, esim. tähän tapaan:

```
Offer/
  - index.jsx <- Komponentin koodi
  - style.css <- Komponentin käyttämät tyylit
```

Tyylien luokkien nimissä voi käyttää komponentin nimeä etuliitteenä, esim. `.Offer__container` ja `.Offer__card`. Tämä vähentää riskiä luokkien nimien yhteentörmäyksessä. Modernimpi ratkaisu tähän ongelmaan on [css-moduulit](https://github.com/css-modules/css-modules).
- Formikin hyödyntäminen lomakkeiden tilanhallinnassa on hyvä idea
- Tämä koodi toistuu aika usein:

```javascript
useQuery(/* ... */, {
  context: { scope: 'api://gappi/api/user' },
})
```

Voisiko `api://gappi/api/user` olla `scope`:n oletusarvo [täällä](https://github.com/Zatyri/g-app/blob/main/src/index.js#L21)?
- Pitääkö access token hakea jokaisen GraphQL-kyselyn yhteydessä? Eikö riittäisi, että se haetaan kun sovellus käynnistyy ja sitä käytetään istunnon (niin kauan kuin selainikkuna on auki) ajan? Käsittääkseni sovelluksen scopen ei pitäisi muuttua käyttäjän istunnon aikana, vaan koko sovelluksen vaatima scope pyydetään yhdellä kirjautumisella
- Myös backend-puolen koodi on selkeästi organisoitua, hienoa!
- GraphQL-skeeman määritykset on organisoitu selkeästi
- [Virheiden loggaus](https://github.com/Zatyri/g-api/blob/main/src/resolvers.js#L103) ja muu käsittely kannattaa tehdä [keskitetysti](https://www.apollographql.com/docs/apollo-server/data/errors/#for-the-client-response). Lisäksi virheen tyyppiä ei kannata hukata, vaan heittää sama virhe uudestaan (`throw new Error(error.message)` sijaan `throw error`)

## Kokonaisuus

Hyödyllinen ja helppokäyttöinen sovellus, jossa on tyylikäs käyttöliittymä. Sovelluksen koodi on kaikin puolin hyvin organisoitua sekä pääosin erittäin helppolukuista ja ylläpidettävää. Katselmoinnissa mainitut ongelmat on ratkaistavissa pienellä refaktoroinnilla. Hyvää työtä!

**Comment by Zatyri** [comment]
Mahtavaa että kerkeätte antamaan tällaista palautetta. Arvostan sitä todella paljon. Mukavaa kuulla, että koodi on pääpiirteiltän järkevää. Korjaukset otan ehdottomasti huomioon tulevissa projekteissa, ja jos kerkeän tai työpaikkani haluaa lähteä kehittämään sovellusta eteenpäin, myös tähän projektiin. 
Kiitos!
